export const verbs = [
    {
        number: 1,
        infinitive: "Arise",
        pastSimple: "Arose",
        pastParticiple: "Arisen",
        translation: "Surgir/ Levantarse",
    },
    {
        number: 2,
        infinitive: "Awake",
        pastSimple: "Awoke",
        pastParticiple: "Awoken",
        translation: "Despertarse",
    },
    {
        number: 3,
        infinitive: "Be/ am/ are/ is",
        pastSimple: "Was / Were",
        pastParticiple: "Been",
        translation: "Ser / Estar",
    },
    {
        number: 4,
        infinitive: "Bear",
        pastSimple: "Bore",
        pastParticiple: "Borne / Born",
        translation: "Soportar/ dar a luz",
    },
    {
        number: 5,
        infinitive: "Beat",
        pastSimple: "Beat",
        pastParticiple: "Beaten",
        translation: "Golpear",
    },
    {
        number: 6,
        infinitive: "Become",
        pastSimple: "Became",
        pastParticiple: "Become",
        translation: "Llegar a Ser",
    },
    {
        number: 7,
        infinitive: "Begin",
        pastSimple: "Began",
        pastParticiple: "Begun",
        translation: "Empezar",
    },
    {
        number: 8,
        infinitive: "Bend",
        pastSimple: "Bent",
        pastParticiple: "Bent",
        translation: "Doblar",
    },
    {
        number: 9,
        infinitive: "Bet",
        pastSimple: "Bet",
        pastParticiple: "Bet",
        translation: "Apostar",
    },
    {
        number: 10,
        infinitive: "Bind",
        pastSimple: "Bound",
        pastParticiple: "Bound",
        translation: "Atar/ encuadernar",
    },
    {
        number: 11,
        infinitive: "Bid",
        pastSimple: "Bid",
        pastParticiple: "Bid",
        translation: "Pujar",
    },
    {
        number: 12,
        infinitive: "Bite",
        pastSimple: "Bit",
        pastParticiple: "Bitten",
        translation: "Morder",
    },
    {
        number: 13,
        infinitive: "Bleed",
        pastSimple: "Bled",
        pastParticiple: "Bled",
        translation: "Sangrar",
    },
    {
        number: 14,
        infinitive: "Blow",
        pastSimple: "Blew",
        pastParticiple: "Blown",
        translation: "Soplar",
    },
    {
        number: 15,
        infinitive: "Break",
        pastSimple: "Broke",
        pastParticiple: "Broken",
        translation: "Romper",
    },
    {
        number: 16,
        infinitive: "Breed",
        pastSimple: "Bred",
        pastParticiple: "Bred",
        translation: "Criar",
    },
    {
        number: 17,
        infinitive: "Bring",
        pastSimple: "Brought",
        pastParticiple: "Brought",
        translation: "Traer Llevar",
    },
    {
        number: 18,
        infinitive: "Broadcast",
        pastSimple: "Broadcast",
        pastParticiple: "Broadcast",
        translation: "Radiar",
    },
    {
        number: 19,
        infinitive: "Build",
        pastSimple: "Built",
        pastParticiple: "Built",
        translation: "Edificar",
    },
    {
        number: 20,
        infinitive: "Burn",
        pastSimple: "Burnt  / Burned",
        pastParticiple: "Burnt  / Burned",
        translation: "Quemar",
    },
    {
        number: 21,
        infinitive: "Burst",
        pastSimple: "Burst",
        pastParticiple: "Burst",
        translation: "Reventar",
    },
    {
        number: 22,
        infinitive: "Buy",
        pastSimple: "Bought",
        pastParticiple: "Bought",
        translation: "Comprar",
    },
    {
        number: 23,
        infinitive: "Can",
        pastSimple: "Could",
        pastParticiple: "",
        translation: "Poder",
    },
    {
        number: 24,
        infinitive: "Cast",
        pastSimple: "Cast",
        pastParticiple: "Cast",
        translation: "Arrojar",
    },
    {
        number: 25,
        infinitive: "Catch",
        pastSimple: "Caught",
        pastParticiple: "Caught",
        translation: "Coger",
    },
    {
        number: 26,
        infinitive: "Come",
        pastSimple: "Came",
        pastParticiple: "Come",
        translation: "Venir",
    },
    {
        number: 27,
        infinitive: "Cost",
        pastSimple: "Cost",
        pastParticiple: "Cost",
        translation: "Costar",
    },
    {
        number: 28,
        infinitive: "Cut",
        pastSimple: "Cut",
        pastParticiple: "Cut",
        translation: "Cortar",
    },
    {
        number: 29,
        infinitive: "Choose",
        pastSimple: "Chose",
        pastParticiple: "Chosen",
        translation: "Elegir",
    },
    {
        number: 30,
        infinitive: "Cling",
        pastSimple: "Clung",
        pastParticiple: "Clung",
        translation: "Agarrarse",
    },
    {
        number: 31,
        infinitive: "Creep",
        pastSimple: "Crept",
        pastParticiple: "Crept",
        translation: "Arrastrarse",
    },
    {
        number: 32,
        infinitive: "Deal",
        pastSimple: "Dealt",
        pastParticiple: "Dealt",
        translation: "Tratar",
    },
    {
        number: 33,
        infinitive: "Dig",
        pastSimple: "Dug",
        pastParticiple: "Dug",
        translation: "Cavar",
    },
    {
        number: 34,
        infinitive: "Do  (Does)",
        pastSimple: "Did",
        pastParticiple: "Done",
        translation: "Hacer",
    },
    {
        number: 35,
        infinitive: "Draw",
        pastSimple: "Drew",
        pastParticiple: "Drawn",
        translation: "Dibujar",
    },
    {
        number: 36,
        infinitive: "Dream",
        pastSimple: "Dreamt /Dreamed",
        pastParticiple: "Dreamt /Dreamed",
        translation: "Soñar",
    },
    {
        number: 37,
        infinitive: "Drink",
        pastSimple: "Drank",
        pastParticiple: "Drunk",
        translation: "Beber",
    },
    {
        number: 38,
        infinitive: "Drive",
        pastSimple: "Drove",
        pastParticiple: "Driven",
        translation: "Conducir",
    },
    {
        number: 39,
        infinitive: "Eat",
        pastSimple: "Ate",
        pastParticiple: "Eaten",
        translation: "Comer",
    },
    {
        number: 40,
        infinitive: "Fall",
        pastSimple: "Fell",
        pastParticiple: "Fallen",
        translation: "Caer",
    },
    {
        number: 41,
        infinitive: "Feed",
        pastSimple: "Fed",
        pastParticiple: "Fed",
        translation: "Alimentar",
    },
    {
        number: 42,
        infinitive: "Feel",
        pastSimple: "Felt",
        pastParticiple: "Felt",
        translation: "Sentir",
    },
    {
        number: 43,
        infinitive: "Fight",
        pastSimple: "Fought",
        pastParticiple: "Fought",
        translation: "Luchar",
    },
    {
        number: 44,
        infinitive: "Find",
        pastSimple: "Found",
        pastParticiple: "Found",
        translation: "Encontrar",
    },
    {
        number: 45,
        infinitive: "Flee",
        pastSimple: "Fled",
        pastParticiple: "Fled",
        translation: "Huir",
    },
    {
        number: 46,
        infinitive: "Fly",
        pastSimple: "Flew",
        pastParticiple: "Flown",
        translation: "Volar",
    },
    {
        number: 47,
        infinitive: "Forbid",
        pastSimple: "Forbade",
        pastParticiple: "Forbidden",
        translation: "Prohibir",
    },
    {
        number: 48,
        infinitive: "Forget",
        pastSimple: "Forgot",
        pastParticiple: "Forgotten",
        translation: "Olvidar",
    },
    {
        number: 49,
        infinitive: "Forgive",
        pastSimple: "Forgave",
        pastParticiple: "Forgiven",
        translation: "Perdonar",
    },
    {
        number: 50,
        infinitive: "Freeze",
        pastSimple: "Froze",
        pastParticiple: "Frozen",
        translation: "Helar",
    },
    {
        number: 51,
        infinitive: "Get",
        pastSimple: "Got",
        pastParticiple: "Got / Gotten",
        translation: "Obtener",
    },
    {
        number: 52,
        infinitive: "Give",
        pastSimple: "Gave",
        pastParticiple: "Given",
        translation: "Dar",
    },
    {
        number: 53,
        infinitive: "Go (Goes)",
        pastSimple: "Went",
        pastParticiple: "Gone",
        translation: "Ir",
    },
    {
        number: 54,
        infinitive: "Grow",
        pastSimple: "Grew",
        pastParticiple: "Grown",
        translation: "Crecer",
    },
    {
        number: 55,
        infinitive: "Grind",
        pastSimple: "Ground",
        pastParticiple: "Ground",
        translation: "Moler",
    },
    {
        number: 56,
        infinitive: "Hang",
        pastSimple: "Hung",
        pastParticiple: "Hung",
        translation: "Colgar",
    },
    {
        number: 57,
        infinitive: "Have",
        pastSimple: "Had",
        pastParticiple: "Had",
        translation: "Haber / Tener",
    },
    {
        number: 58,
        infinitive: "Hear",
        pastSimple: "Heard",
        pastParticiple: "Heard",
        translation: "Oir",
    },
    {
        number: 59,
        infinitive: "Hide",
        pastSimple: "Hid",
        pastParticiple: "Hidden",
        translation: "Ocultar",
    },
    {
        number: 60,
        infinitive: "Hit",
        pastSimple: "Hit",
        pastParticiple: "Hit",
        translation: "Golpear",
    },
    {
        number: 61,
        infinitive: "Hold",
        pastSimple: "Held",
        pastParticiple: "Held",
        translation: "Agarrar Celebrar",
    },
    {
        number: 62,
        infinitive: "Hurt",
        pastSimple: "Hurt",
        pastParticiple: "Hurt",
        translation: "Herir",
    },
    {
        number: 63,
        infinitive: "Keep",
        pastSimple: "Kept",
        pastParticiple: "Kept",
        translation: "Conservar",
    },
    {
        number: 64,
        infinitive: "Know",
        pastSimple: "Knew",
        pastParticiple: "Known",
        translation: "Saber Conocer",
    },
    {
        number: 65,
        infinitive: "Kneel",
        pastSimple: "Knelt",
        pastParticiple: "Knelt",
        translation: "Arrodillarse",
    },
    {
        number: 66,
        infinitive: "Knit",
        pastSimple: "Knit",
        pastParticiple: "Knit",
        translation: "Hacer punto",
    },
    {
        number: 67,
        infinitive: "Lay",
        pastSimple: "Laid",
        pastParticiple: "Laid",
        translation: "Poner",
    },
    {
        number: 68,
        infinitive: "Lead",
        pastSimple: "Led",
        pastParticiple: "Led",
        translation: "Conducir",
    },
    {
        number: 69,
        infinitive: "Lean",
        pastSimple: "Leant",
        pastParticiple: "Leant",
        translation: "Apoyarse",
    },
    {
        number: 70,
        infinitive: "Leap",
        pastSimple: "Leapt",
        pastParticiple: "Leapt",
        translation: "Brincar",
    },
    {
        number: 71,
        infinitive: "Learn",
        pastSimple: "Learnt / Learned",
        pastParticiple: "Learnt / Learned",
        translation: "Aprender",
    },
    {
        number: 72,
        infinitive: "Leave",
        pastSimple: "Left",
        pastParticiple: "Left",
        translation: "Dejar",
    },
    {
        number: 73,
        infinitive: "Lend",
        pastSimple: "Lent",
        pastParticiple: "Lent",
        translation: "Prestar",
    },
    {
        number: 74,
        infinitive: "Let",
        pastSimple: "Let",
        pastParticiple: "Let",
        translation: "Permitir",
    },
    {
        number: 75,
        infinitive: "Lie",
        pastSimple: "Lay",
        pastParticiple: "Lain",
        translation: "Echarse",
    },
    {
        number: 76,
        infinitive: "Light",
        pastSimple: "Lit",
        pastParticiple: "Lit",
        translation: "Encender",
    },
    {
        number: 77,
        infinitive: "Lose",
        pastSimple: "Lost",
        pastParticiple: "Lost",
        translation: "Perder",
    },
    {
        number: 78,
        infinitive: "Make",
        pastSimple: "Made",
        pastParticiple: "Made",
        translation: "Hacer",
    },
    {
        number: 79,
        infinitive: "Mean",
        pastSimple: "Meant",
        pastParticiple: "Meant",
        translation: "Significar",
    },
    {
        number: 80,
        infinitive: "Meet",
        pastSimple: "Met",
        pastParticiple: "Met",
        translation: "Encontrar",
    },
    {
        number: 81,
        infinitive: "Mistake",
        pastSimple: "Mistook",
        pastParticiple: "Mistaken",
        translation: "Equivocar",
    },
    {
        number: 82,
        infinitive: "Overcome",
        pastSimple: "Overcame",
        pastParticiple: "Overcome",
        translation: "Vencer",
    },
    {
        number: 83,
        infinitive: "Pay",
        pastSimple: "Paid",
        pastParticiple: "Paid",
        translation: "Pagar",
    },
    {
        number: 84,
        infinitive: "Put",
        pastSimple: "Put",
        pastParticiple: "Put",
        translation: "Poner",
    },
    {
        number: 85,
        infinitive: "Read",
        pastSimple: "Read",
        pastParticiple: "Read",
        translation: "Leer",
    },
    {
        number: 86,
        infinitive: "Ride",
        pastSimple: "Rode",
        pastParticiple: "Ridden",
        translation: "Montar",
    },
    {
        number: 87,
        infinitive: "Ring",
        pastSimple: "Rang",
        pastParticiple: "Rung",
        translation: "Llamar",
    },
    {
        number: 88,
        infinitive: "Rise",
        pastSimple: "Rose",
        pastParticiple: "Risen",
        translation: "Levantarse",
    },
    {
        number: 89,
        infinitive: "Run",
        pastSimple: "Ran",
        pastParticiple: "Run",
        translation: "Correr",
    },
    {
        number: 90,
        infinitive: "Say",
        pastSimple: "Said",
        pastParticiple: "Said",
        translation: "Decir",
    },
    {
        number: 91,
        infinitive: "See",
        pastSimple: "Saw",
        pastParticiple: "Seen",
        translation: "Ver",
    },
    {
        number: 92,
        infinitive: "Seek",
        pastSimple: "Sought",
        pastParticiple: "Sought",
        translation: "Buscar",
    },
    {
        number: 93,
        infinitive: "Sell",
        pastSimple: "Sold",
        pastParticiple: "Sold",
        translation: "Vender",
    },
    {
        number: 94,
        infinitive: "Send",
        pastSimple: "Sent",
        pastParticiple: "Sent",
        translation: "Enviar",
    },
    {
        number: 95,
        infinitive: "Set",
        pastSimple: "Set",
        pastParticiple: "Set",
        translation: "Poner(se)",
    },
    {
        number: 96,
        infinitive: "Sew",
        pastSimple: "Sewed",
        pastParticiple: "Sewed / Sewn",
        translation: "Coser",
    },
    {
        number: 97,
        infinitive: "Shake",
        pastSimple: "Shook",
        pastParticiple: "Shaken",
        translation: "Sacudir",
    },
    {
        number: 98,
        infinitive: "Shear",
        pastSimple: "Shore",
        pastParticiple: "Shorn",
        translation: "Esquilar",
    },
    {
        number: 99,
        infinitive: "Shine",
        pastSimple: "Shone",
        pastParticiple: "Shone",
        translation: "Brillar",
    },
    {
        number: 100,
        infinitive: "Shoot",
        pastSimple: "Shot",
        pastParticiple: "Shot",
        translation: "Disparar",
    },
    {
        number: 101,
        infinitive: "Show",
        pastSimple: "Showed",
        pastParticiple: "Shown",
        translation: "Mostrar",
    },
    {
        number: 102,
        infinitive: "Shrink",
        pastSimple: "Shrank",
        pastParticiple: "Shrunk",
        translation: "Encogerse",
    },
    {
        number: 103,
        infinitive: "Shut",
        pastSimple: "Shut",
        pastParticiple: "Shut",
        translation: "Cerrar",
    },
    {
        number: 104,
        infinitive: "Sing",
        pastSimple: "Sang",
        pastParticiple: "Sung",
        translation: "Cantar",
    },
    {
        number: 105,
        infinitive: "Sink",
        pastSimple: "Sank",
        pastParticiple: "Sunk",
        translation: "Hundir",
    },
    {
        number: 106,
        infinitive: "Sit",
        pastSimple: "Sat",
        pastParticiple: "Sat",
        translation: "Sentarse",
    },
    {
        number: 107,
        infinitive: "Sleep",
        pastSimple: "Slept",
        pastParticiple: "Slept",
        translation: "Dormir",
    },
    {
        number: 108,
        infinitive: "Slide",
        pastSimple: "Slid",
        pastParticiple: "Slid",
        translation: "Resbalar",
    },
    {
        number: 109,
        infinitive: "Smell",
        pastSimple: "Smelt",
        pastParticiple: "Smelt",
        translation: "Oler",
    },
    {
        number: 110,
        infinitive: "Sow",
        pastSimple: "Sowed",
        pastParticiple: "Sowed / Sown",
        translation: "Sembrar",
    },
    {
        number: 111,
        infinitive: "Speak",
        pastSimple: "Spoke",
        pastParticiple: "Spoken",
        translation: "Hablar",
    },
    {
        number: 112,
        infinitive: "Speed",
        pastSimple: "Sped",
        pastParticiple: "Sped",
        translation: "Acelerar",
    },
    {
        number: 113,
        infinitive: "Spell",
        pastSimple: "Spelt",
        pastParticiple: "Spelt",
        translation: "Deletrear",
    },
    {
        number: 114,
        infinitive: "Spend",
        pastSimple: "Spent",
        pastParticiple: "Spent",
        translation: "Gastar",
    },
    {
        number: 115,
        infinitive: "Spill",
        pastSimple: "Spilt / Spilled",
        pastParticiple: "Spilt / Spilled",
        translation: "Derramar",
    },
    {
        number: 116,
        infinitive: "Spin",
        pastSimple: "Spun",
        pastParticiple: "Spun",
        translation: "Hilar",
    },
    {
        number: 117,
        infinitive: "Spit",
        pastSimple: "Spat",
        pastParticiple: "Spat",
        translation: "Escupir",
    },
    {
        number: 118,
        infinitive: "Split",
        pastSimple: "Split",
        pastParticiple: "Split",
        translation: "Hender / partir / rajar",
    },
    {
        number: 119,
        infinitive: "Spoil",
        pastSimple: "Spoilt / Spoiled",
        pastParticiple: "Spoilt / Spoiled",
        translation: "Estropear",
    },
    {
        number: 120,
        infinitive: "Spread",
        pastSimple: "Spread",
        pastParticiple: "Spread",
        translation: "Extender",
    },
    {
        number: 121,
        infinitive: "Spring",
        pastSimple: "Sprang",
        pastParticiple: "Sprung",
        translation: "Saltar",
    },
    {
        number: 122,
        infinitive: "Stand",
        pastSimple: "Stood",
        pastParticiple: "Stood",
        translation: "Estar en pie",
    },
    {
        number: 123,
        infinitive: "Steal",
        pastSimple: "Stole",
        pastParticiple: "Stolen",
        translation: "Robar",
    },
    {
        number: 124,
        infinitive: "Stick",
        pastSimple: "Stuck",
        pastParticiple: "Stuck",
        translation: "Pegar Engomar",
    },
    {
        number: 125,
        infinitive: "Sting",
        pastSimple: "Stung",
        pastParticiple: "Stung",
        translation: "Picar",
    },
    {
        number: 126,
        infinitive: "Stink",
        pastSimple: "Stank/Stunk",
        pastParticiple: "Stunk",
        translation: "Apestar",
    },
    {
        number: 127,
        infinitive: "Stride",
        pastSimple: "Strode",
        pastParticiple: "Stridden",
        translation: "Dar zancadas",
    },
    {
        number: 128,
        infinitive: "Strike",
        pastSimple: "Struck",
        pastParticiple: "Struck",
        translation: "Golpear",
    },
    {
        number: 129,
        infinitive: "Swear",
        pastSimple: "Swore",
        pastParticiple: "Sworn",
        translation: "Jurar",
    },
    {
        number: 130,
        infinitive: "Sweat",
        pastSimple: "Sweat",
        pastParticiple: "Sweat",
        translation: "Sudar",
    },
    {
        number: 131,
        infinitive: "Sweep",
        pastSimple: "Swept",
        pastParticiple: "Swept",
        translation: "Barrer",
    },
    {
        number: 132,
        infinitive: "Swell",
        pastSimple: "Swelled",
        pastParticiple: "Swollen",
        translation: "Hinchar",
    },
    {
        number: 133,
        infinitive: "Swim",
        pastSimple: "Swam",
        pastParticiple: "Swum",
        translation: "Nadar",
    },
    {
        number: 134,
        infinitive: "Swing",
        pastSimple: "Swung",
        pastParticiple: "Swung",
        translation: "Columpiarse",
    },
    {
        number: 135,
        infinitive: "Take",
        pastSimple: "Took",
        pastParticiple: "Taken",
        translation: "Coger",
    },
    {
        number: 136,
        infinitive: "Teach",
        pastSimple: "Taught",
        pastParticiple: "Taught",
        translation: "Enseñar",
    },
    {
        number: 137,
        infinitive: "Tear",
        pastSimple: "Tore",
        pastParticiple: "Torn",
        translation: "Rasgar",
    },
    {
        number: 138,
        infinitive: "Tell",
        pastSimple: "Told",
        pastParticiple: "Told",
        translation: "Decir",
    },
    {
        number: 139,
        infinitive: "Think",
        pastSimple: "Thought",
        pastParticiple: "Thought",
        translation: "Pensar",
    },
    {
        number: 140,
        infinitive: "Throw",
        pastSimple: "Threw",
        pastParticiple: "Thrown",
        translation: "Arrojar Tirar",
    },
    {
        number: 141,
        infinitive: "Thrust",
        pastSimple: "Thrust",
        pastParticiple: "Thrust",
        translation: "Introducir",
    },
    {
        number: 142,
        infinitive: "Tread",
        pastSimple: "Trod",
        pastParticiple: "Trodden",
        translation: "Pisar/ hollar",
    },
    {
        number: 143,
        infinitive: "Understand",
        pastSimple: "Understood",
        pastParticiple: "Understood",
        translation: "Entender",
    },
    {
        number: 144,
        infinitive: "Undergo",
        pastSimple: "Underwent",
        pastParticiple: "Undergone",
        translation: "Sufrir",
    },
    {
        number: 145,
        infinitive: "Undertake",
        pastSimple: "Undertook",
        pastParticiple: "Undertaken",
        translation: "Emprender",
    },
    {
        number: 146,
        infinitive: "Wake",
        pastSimple: "Woke",
        pastParticiple: "Woken",
        translation: "Despertarse",
    },
    {
        number: 147,
        infinitive: "Wear",
        pastSimple: "Wore",
        pastParticiple: "Worn",
        translation: "Llevar puesto",
    },
    {
        number: 148,
        infinitive: "Weave",
        pastSimple: "Wove",
        pastParticiple: "Woven",
        translation: "Tejer",
    },
    {
        number: 149,
        infinitive: "Weep",
        pastSimple: "Wept",
        pastParticiple: "Wept",
        translation: "Llorar",
    },
    {
        number: 150,
        infinitive: "Wet",
        pastSimple: "Wet",
        pastParticiple: "Wet",
        translation: "Mojar",
    },
    {
        number: 151,
        infinitive: "Win",
        pastSimple: "Won",
        pastParticiple: "Won",
        translation: "Ganar",
    },
    {
        number: 152,
        infinitive: "Wind",
        pastSimple: "Wound",
        pastParticiple: "Wound",
        translation: "Enrollar",
    },
    {
        number: 153,
        infinitive: "Withdraw",
        pastSimple: "Withdrew",
        pastParticiple: "Withdrawn",
        translation: "Retirarse",
    },
    {
        number: 154,
        infinitive: "Wring",
        pastSimple: "Wrung",
        pastParticiple: "Wrung",
        translation: "Torcer",
    },
    {
        number: 155,
        infinitive: "Write",
        pastSimple: "Wrote",
        pastParticiple: "Written",
        translation: "Escribir",
    },
];
